#!/bin/bash
# systemadmin.es

printusage()
{
        echo "$0 -v hitrate/getrate -H host -w warning -c critical"
        echo ""
}

while getopts 'v:H:w:c:' OPTION
do
  case $OPTION in
  v)    vflag=1
        vval="$OPTARG"
        ;;
  H)    hflag=1
        hval="$OPTARG"
        ;;
  C)    cflag=1
        cval="$OPTARG"
        ;;
  w)    warningflag=1
        warningval="$OPTARG"
        ;;
  c)    criticalflag=1
        criticalval="$OPTARG"
        ;;
  ?)    echo Argument invalid: $OPTION
        printusage
        exit 3
        ;;
  esac
done
#VAR=`(
#echo open localhost 11211
#sleep 2
#echo "stats"
#sleep 1
#echo "quit"
#sleep 1
#) | telnet 2>&1`

#echo $VAR2

#VAR2=echo $VAR|awk -F'get_hits' '{print $2}'|awk '{print $1}'

#$GET_MISSES= echo $VAR|awk -F'get_misses' '{print $2}'|awk '{print $1}'
#$CMD_SET= echo $VAR|awk -F'cmd_set' '{print $2}'|awk '{print $1}'
#$CMD_GET= echo $VAR|awk -F'cmd_get' '{print $2}'|awk '{print $1}'

#exit
case $vval in
        hitrate)
        HITS=$GET_HITS
        MISSES=$GET_MISSES
	SUMHITMISS=0
        SUMHITMISS=$(echo "(${HITS}*100)+(${HITS}+${MISSES})" | bc -l)
	echo $SUMHITMISS	
	exit
        if [ $SUMHITMISS -eq 0 ]
        then
                HITRATE=0
        else
                HITRATE=$(echo "(${HITS}*100)/(${HITS}+${MISSES})" | bc -l)
        fi

        DISPHR=$(echo $HITRATE+0.5 | bc -l | sed 's/\..*$//ig')

        if [ -z "$DISPHR" ];
        then
                DISPHR=0
        fi

        if [ -z "$HITRATE" ];
        then
                echo "UNKNOWN  - ERROR"
                exit 3
        fi

        echo "memcached hit rate: ${DISPHR}%|hitrate=$HITRATE"
        ;;

        getrate)
        CMDSET=$CMD_SET
        CMDGET=$CMD_GET

        SUMGETSET=$(echo "(${CMDGET}*100)+(${CMDGET}+${CMDSET})" | bc -l)
	echo ----$SUMGETSET
	echo $SUMGETSET
        if [ $SUMGETSET -eq 0 ];
        then
                GETRATE=0
        else
                GETRATE=$(echo "(${CMDGET}*100)/(${CMDGET}+${CMDSET})" | bc -l)
        fi

        DISPGR=$(echo $GETRATE+0.5 | bc -l | sed 's/\..*$//ig')

        if [ -z "$DISPGR" ];
        then
                DISPGR=0
        fi

        if [ -z "$GETRATE" ];
        then
                echo "UNKNOWN  - ERROR"
                exit 3
        fi

        echo "memcached get rate: ${DISPGR}%|getrate=$GETRATE"
        ;;
        *)
                echo UNKNOWN - no parameter
                exit 3
        ;;
esac

exit 0

