#!/bin/bash
REVISION=1
PROGNAME="check-heartbeat-master"
PROGPATH=`echo $0 | /bin/sed -e 's,[\\/][^\\/][^\\/]*$,,'`

NODE_NAME=`uname -n`
CL_ST='/usr/bin/cl_status'

#nagios error codes
#. $PROGPATH/utils.sh 
OK=0
WARNING=1
CRITICAL=2
UNKNOWN=3

usage () {
    echo "\
Nagios plugin to heartbeat.

Usage:
  $PROGNAME 
  $PROGNAME [--help | -h]
  $PROGNAME [--version | -v]

Options:
  --help -l	Print this help information
  --version -v  Print version of plugin
"
}
VERSION=`rpm -qa|grep PDI|awk -F'.' '{print $3}'`
  echo "PDI-Version:$VERSION"
  exit $OK
