#!/bin/bash
REVISION=1
PROGNAME="check-heartbeat-master"
PROGPATH=`echo $0 | /bin/sed -e 's,[\\/][^\\/][^\\/]*$,,'`
PORT=$2
IPADDR=$4
declare -i CRIT_VAL=$6
declare -i WAR_VAL=$8

NODE_NAME=`uname -n`
CL_ST='/usr/bin/cl_status'

#nagios error codes
#. $PROGPATH/utils.sh 
OK=0
WARNING=1
CRITICAL=2
UNKNOWN=3

/usr/local/nagios/plugins/check-heartbeat-master >/dev/null
IS_MASTER=$?

if [[ $IS_MASTER -eq  $OK ]]; then
valor=`/usr/local/nagios/plugins/check_port -p $PORT -h $IPADDR -c $CRIT_VAL -w $WAR_VAL `
res=$?
else 
valor="WARNING:check HEARBEAT IS MASTER=$IS_MASTER?"
res=$WARNING
fi

echo $valor
exit $res 

