#!/bin/bash
[ $# -ne 1 ] && { echo "Parametro incorrecto" ; exit 2 ; }
NV=(172.21.0.206 172.21.0.207)
MR=(172.21.0.238 172.21.0.239)
OK=0
WARNING=1
CRITICAL=2
UNKNOWN=3
PORT=5672


if [ "$1" == "nv" ]; then
echo NV
CLUSTER=("${NV[@]}")
else
echo mr
CLUSTER=("${MR[@]}")
fi


total=0
for i in ${CLUSTER[*]}; do  
valor=`/usr/local/nagios/plugins/check_port -p $PORT -h $i -c 4 -w 2` 
res=$?
[ $res -eq 0 ] && total=`expr $total + 1 ` 
done
echo "Conexiones abiertas: $total"
if [ $total -eq 2 ]; then 
exit $OK
else
exit $CRIT
fi

