#!/bin/bash

RES_OK=0
RES_WARN=1
RES_CRIT=2
RES_UNK=3


function usage {
    echo "Usage: $0 host user pass crit_per crit_slow crit_threads"
    exit $RES_UNK
}


if [ $# -ne 3 ]
then
    usage
fi


query=$(mysql --skip-reconnect -h$1 -u$2 -p$3 -e"show status;" | tail -n1)
#echo $query
get_error=`echo $query|grep -io ERROR |wc -l `
#echo $get_error

if [ $get_error -gt 0 ]
then
    echo "MySQL CRITICAL:$get_error"
    exit $RES_CRIT
else
    echo "MySQL OK"
    exit $RES_OK
fi

