#!/bin/bash
# splunk        Init script for running the splunk client daemon
#
# chkconfig: - 98 02
#
# description: 
# processname: splunkd
# config: /opt/splunkforwarder/etc/splunk-launch.conf

PATH=/usr/bin:/sbin:/bin:/usr/sbin:/opt/splunkforwarder/bin
export PATH

splunkd=${PUPPETD-/opt/splunkforwarder/bin/splunk}

OPTS='--answer-yes --no-prompt --accept-license'

start() {
    $splunkd start ${OPTS}
}

stop() {
    $splunkd stop ${OPTS}
}

restart() {
    $splunkd restart ${OPTS}
}

status() {
    $splunkd status ${OPTS}
}

case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart)
        restart
    ;;
    status)
        status
    ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 1
esac

exit 
